# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wonderwoman/desktop/SEAL_N/SEAL-master/Final_test_functions

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wonderwoman/desktop/SEAL_N/SEAL-master/Final_test_functions

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wonderwoman/desktop/SEAL_N/SEAL-master/Final_test_functions/CMakeFiles /home/wonderwoman/desktop/SEAL_N/SEAL-master/Final_test_functions/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wonderwoman/desktop/SEAL_N/SEAL-master/Final_test_functions/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test1

# Build rule for target.
test1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test1
.PHONY : test1

# fast build rule for target.
test1/fast:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/build
.PHONY : test1/fast

Deep_neural_nw.o: Deep_neural_nw.cpp.o

.PHONY : Deep_neural_nw.o

# target to build an object file
Deep_neural_nw.cpp.o:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Deep_neural_nw.cpp.o
.PHONY : Deep_neural_nw.cpp.o

Deep_neural_nw.i: Deep_neural_nw.cpp.i

.PHONY : Deep_neural_nw.i

# target to preprocess a source file
Deep_neural_nw.cpp.i:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Deep_neural_nw.cpp.i
.PHONY : Deep_neural_nw.cpp.i

Deep_neural_nw.s: Deep_neural_nw.cpp.s

.PHONY : Deep_neural_nw.s

# target to generate assembly for a file
Deep_neural_nw.cpp.s:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Deep_neural_nw.cpp.s
.PHONY : Deep_neural_nw.cpp.s

Discrete_neural_nw.o: Discrete_neural_nw.cpp.o

.PHONY : Discrete_neural_nw.o

# target to build an object file
Discrete_neural_nw.cpp.o:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Discrete_neural_nw.cpp.o
.PHONY : Discrete_neural_nw.cpp.o

Discrete_neural_nw.i: Discrete_neural_nw.cpp.i

.PHONY : Discrete_neural_nw.i

# target to preprocess a source file
Discrete_neural_nw.cpp.i:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Discrete_neural_nw.cpp.i
.PHONY : Discrete_neural_nw.cpp.i

Discrete_neural_nw.s: Discrete_neural_nw.cpp.s

.PHONY : Discrete_neural_nw.s

# target to generate assembly for a file
Discrete_neural_nw.cpp.s:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Discrete_neural_nw.cpp.s
.PHONY : Discrete_neural_nw.cpp.s

Performance_test.o: Performance_test.cpp.o

.PHONY : Performance_test.o

# target to build an object file
Performance_test.cpp.o:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Performance_test.cpp.o
.PHONY : Performance_test.cpp.o

Performance_test.i: Performance_test.cpp.i

.PHONY : Performance_test.i

# target to preprocess a source file
Performance_test.cpp.i:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Performance_test.cpp.i
.PHONY : Performance_test.cpp.i

Performance_test.s: Performance_test.cpp.s

.PHONY : Performance_test.s

# target to generate assembly for a file
Performance_test.cpp.s:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Performance_test.cpp.s
.PHONY : Performance_test.cpp.s

Sigmoid.o: Sigmoid.cpp.o

.PHONY : Sigmoid.o

# target to build an object file
Sigmoid.cpp.o:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Sigmoid.cpp.o
.PHONY : Sigmoid.cpp.o

Sigmoid.i: Sigmoid.cpp.i

.PHONY : Sigmoid.i

# target to preprocess a source file
Sigmoid.cpp.i:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Sigmoid.cpp.i
.PHONY : Sigmoid.cpp.i

Sigmoid.s: Sigmoid.cpp.s

.PHONY : Sigmoid.s

# target to generate assembly for a file
Sigmoid.cpp.s:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Sigmoid.cpp.s
.PHONY : Sigmoid.cpp.s

Sign_algo1.o: Sign_algo1.cpp.o

.PHONY : Sign_algo1.o

# target to build an object file
Sign_algo1.cpp.o:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Sign_algo1.cpp.o
.PHONY : Sign_algo1.cpp.o

Sign_algo1.i: Sign_algo1.cpp.i

.PHONY : Sign_algo1.i

# target to preprocess a source file
Sign_algo1.cpp.i:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Sign_algo1.cpp.i
.PHONY : Sign_algo1.cpp.i

Sign_algo1.s: Sign_algo1.cpp.s

.PHONY : Sign_algo1.s

# target to generate assembly for a file
Sign_algo1.cpp.s:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Sign_algo1.cpp.s
.PHONY : Sign_algo1.cpp.s

Sign_algo2.o: Sign_algo2.cpp.o

.PHONY : Sign_algo2.o

# target to build an object file
Sign_algo2.cpp.o:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Sign_algo2.cpp.o
.PHONY : Sign_algo2.cpp.o

Sign_algo2.i: Sign_algo2.cpp.i

.PHONY : Sign_algo2.i

# target to preprocess a source file
Sign_algo2.cpp.i:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Sign_algo2.cpp.i
.PHONY : Sign_algo2.cpp.i

Sign_algo2.s: Sign_algo2.cpp.s

.PHONY : Sign_algo2.s

# target to generate assembly for a file
Sign_algo2.cpp.s:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/Sign_algo2.cpp.s
.PHONY : Sign_algo2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test1"
	@echo "... edit_cache"
	@echo "... Deep_neural_nw.o"
	@echo "... Deep_neural_nw.i"
	@echo "... Deep_neural_nw.s"
	@echo "... Discrete_neural_nw.o"
	@echo "... Discrete_neural_nw.i"
	@echo "... Discrete_neural_nw.s"
	@echo "... Performance_test.o"
	@echo "... Performance_test.i"
	@echo "... Performance_test.s"
	@echo "... Sigmoid.o"
	@echo "... Sigmoid.i"
	@echo "... Sigmoid.s"
	@echo "... Sign_algo1.o"
	@echo "... Sign_algo1.i"
	@echo "... Sign_algo1.s"
	@echo "... Sign_algo2.o"
	@echo "... Sign_algo2.i"
	@echo "... Sign_algo2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

